currencies_list = ['BTC', 'BCH', 'ETH', 'LTC', 'XRP', 'AED', 'AFN', 'ALL', 'AMD', 'ANG', 'AOA', 'ARS', 'AUD', 'AWG',
                   'AZN', 'BAM', 'BBD', 'BDT', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BRL', 'BSD', 'BTN', 'BUSD',
                   'BWP', 'BYN', 'BZD', 'CAD', 'CDF', 'CHF', 'CLF', 'CLP', 'CNY', 'COP', 'CRC', 'CUP', 'CVE', 'CZK',
                   'DAI', 'DJF', 'DKK', 'DOGE', 'DOP', 'DZD', 'EGP', 'ETB', 'EUR', 'FJD', 'FKP', 'GBP', 'GEL', 'GHS',
                   'GIP', 'GMD', 'GNF', 'GTQ', 'GUSD', 'GYD', 'HKD', 'HNL', 'HRK', 'HTG', 'HUF', 'IDR', 'ILS', 'INR',
                   'IQD', 'IRR', 'ISK', 'JEP', 'JMD', 'JOD', 'JPY', 'KES', 'KGS', 'KHR', 'KMF', 'KPW', 'KRW', 'KWD',
                   'KYD', 'KZT', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'LYD', 'MAD', 'MDL', 'MGA', 'MKD', 'MMK', 'MNT',
                   'MOP', 'MRU', 'MUR', 'MVR', 'MWK', 'MXN', 'MYR', 'MZN', 'NAD', 'NGN', 'NIO', 'NOK', 'NPR', 'NZD',
                   'OMR', 'PAB', 'PAX', 'PEN', 'PGK', 'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF',
                   'SAR', 'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP', 'SLL', 'SOS', 'SRD', 'STN', 'SVC', 'SYP', 'SZL',
                   'THB', 'TJS', 'TMT', 'TND', 'TOP', 'TRY', 'TTD', 'TWD', 'TZS', 'UAH', 'UGX', 'USD', 'USDC', 'UYU',
                   'UZS', 'VES', 'VND', 'VUV', 'WBTC', 'SHIB', 'WST', 'XAF', 'XAG', 'XAU', 'XCD', 'XPF', 'XOF', 'YER',
                   'ZAR', 'ZMW', 'ZWL', 'btc', 'bch', 'eth', 'ltc', 'xrp', 'aed', 'afn', 'all', 'amd', 'ang', 'aoa',
                   'ars', 'aud', 'awg', 'azn', 'bam', 'bbd', 'bdt', 'bgn', 'bhd', 'bif', 'bmd', 'bnd', 'bob', 'brl',
                   'bsd', 'btn', 'busd', 'bwp', 'byn', 'bzd', 'cad', 'cdf', 'chf', 'clf', 'clp', 'cny', 'cop', 'crc',
                   'cup', 'cve', 'czk', 'dai', 'djf', 'dkk', 'doge', 'dop', 'dzd', 'egp', 'etb', 'eur', 'fjd', 'fkp',
                   'gbp', 'gel', 'ghs', 'gip', 'gmd', 'gnf', 'gtq', 'gusd', 'gyd', 'hkd', 'hnl', 'hrk', 'htg', 'huf',
                   'idr', 'ils', 'inr', 'iqd', 'irr', 'isk', 'jep', 'jmd', 'jod', 'jpy', 'kes', 'kgs', 'khr', 'kmf',
                   'kpw', 'krw', 'kwd', 'kyd', 'kzt', 'lak', 'lbp', 'lkr', 'lrd', 'lsl', 'lyd', 'mad', 'mdl', 'mga',
                   'mkd', 'mmk', 'mnt', 'mop', 'mru', 'mur', 'mvr', 'mwk', 'mxn', 'myr', 'mzn', 'nad', 'ngn', 'nio',
                   'nok', 'npr', 'nzd', 'omr', 'pab', 'pax', 'pen', 'pgk', 'php', 'pkr', 'pln', 'pyg', 'qar', 'ron',
                   'rsd', 'rub', 'rwf', 'sar', 'sbd', 'scr', 'sdg', 'sek', 'sgd', 'shp', 'sll', 'sos', 'srd', 'stn',
                   'svc', 'syp', 'szl', 'thb', 'tjs', 'tmt', 'tnd', 'top', 'try', 'ttd', 'twd', 'tzs', 'uah', 'ugx',
                   'usd', 'usdc', 'uyu', 'uzs', 'ves', 'vnd', 'vuv', 'wbtc', 'shib', 'wst', 'xaf', 'xag', 'xau', 'xcd',
                   'xpf', 'xof', 'yer', 'zar', 'zmw', 'zwl']
